Month7/step2
LosevaMarina/react-burger pull request #3
Opened 2023-03-23 04:26 UTC by LosevaMarina

ModalOverlay срабатывает через раз. Сомневаюсь что верно, 2 дня исправляла, переделала почти все, однако все так же, через раз
А переделывала кучу раз, потому что методом getElementById я искала id="#moduls" #!!!! 
Но и отменять изменения в файлах не стала, слишком много рефакторинга

2023-03-23 14:06 UTC, andryxxa93 requested changes
- У вас неправильный импорт стилей в `ModalOverlay` если его поправить, то оверлей появляется. Но из-за того, что стили у него неправильные, то он не на всю страницу. `height: fit-content;` там не нужен. А вот z-index нужен, иначе подложка будет перекрывать модалку. У модалки тоже необходимо выставить z-index больший чем у подложки.

2023-03-23 21:03 UTC, LosevaMarina commented
у меня нет слов..

2023-03-24 06:34 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

Напомню, что если у вас что-то не получается вы всегда можете обратиться к своему наставнику.

2023-03-24 06:36 UTC, andryxxa93 commented
> у меня нет слов..

Со всеми бывает, вы если где-то застряли и долго не можете решить проблему, то обращайтесь к наставникам - уметь просить о помощи это тоже очень полезный навык 😊

2023-03-30 11:38 UTC, merged